config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  devise_for :users

  namespace :admin do
    root 'products#index'
    resources :products
    resources :categories
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates :name, presence: true, length: {maximum: 250}
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category

  validates :title, presence: true,
            length: { maximum: 250 }

  validates :price, presence: true,
            numericality: { greater_than_or_equal_to: 0.01 }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def destroy
    Category.destroy(params[:id])

    redirect_to admin_categories_path
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      save_picture
      redirect_to [:admin, @product]
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      save_picture
      redirect_to [:admin, @product]
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.destroy(params[:id])
    redirect_to admin_products_url
  end

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :category_id)
  end

  def save_picture
    uploaded_file = params[:product][:picture]

    unless uploaded_file.nil?
      new_file_path = Rails.root.join('public', 'uploads', @product.id.to_s)

      File.open(new_file_path, 'wb') do |file|
        file.write uploaded_file.read
      end
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'

  before_action :authenticate_user!, :admin_user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

  def admin_user
    unless current_user.admin?
      flash[:danger] = "You don't have enough permissions"
      redirect_to root_url
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.paginate(page: params[:page], per_page: 10)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def product_image(id)
    if File.exists? Rails.root.join('public', 'uploads', id.to_s)
      "/uploads/#{id}"
    else
      'coming-soon.png'
    end
  end
end

app/views/admin/categories/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Categories <%= link_to 'Add category', new_admin_category_path, class: 'btn btn-success' %></h1>
  </div>
</div>

<hr />

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th style="width: 100px;">Actions</th>
  </tr>

  <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td>
          <%= link_to 'Delete', admin_category_path(category), method: :delete, data: {confirm: 'Are you sure?'} %>
        </td>
      </tr>
  <% end %>
</table>

app/views/admin/categories/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>New Category</h1>
  </div>
</div>

<hr />

<%= form_for [:admin, @category], html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group <%= 'has-error' if @category.errors[:name].any? %>">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @category, field_name: :name %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product], html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group <%= 'has-error' if @product.errors[:title].any? %>">
      <%= f.label :title, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @product, field_name: :title %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @product.errors[:description].any? %>">
      <%= f.label :description, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :description, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @product, field_name: :description %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @product.errors[:price].any? %>">
      <%= f.label :price, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :price, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @product, field_name: :price %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @product.errors[:category_id].any? %>">
      <%= f.label :category_id, 'Category', class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.collection_select :category_id, Category.all, :id, :name, {}, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @product, field_name: :category_id %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @product.errors[:picture].any? %>">
      <%= f.label :picture, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.file_field :picture %>
        <%= render 'shared/field_errors', object: @product, field_name: :picture %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

app/views/admin/products/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Edit Product</h1>
  </div>
</div>

<hr />

<%= render 'form' %>

app/views/admin/products/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Products <%= link_to 'New Product', new_admin_product_path, class: 'btn btn-success' %></h1>
  </div>
</div>

<hr />

<table class="table table-striped">
  <tr>
    <th>Image</th>
    <th>Title</th>
    <th>Description</th>
    <th>Price</th>
    <th>Category</th>
    <th>Actions</th>
  </tr>

  <% @products.each do |product| %>
      <tr>
        <td><%= image_tag "/uploads/#{product.id}", size: '100' %></td>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.category.name %></td>
        <td>
          <%= link_to 'View', admin_product_path(product) %>
          <%= link_to 'Edit', edit_admin_product_path(product) %>
          <%= link_to 'Delete', admin_product_path(product),
                      method: :delete,
                      data: {confirm: 'Do you want to remove this product?'} %>
        </td>
      </tr>
  <% end %>

</table>

app/views/admin/products/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>New Product</h1>
  </div>
</div>

<hr />

<%= render 'form' %>

app/views/admin/products/show.html.erb
<h1><%= @product.title %></h1>
<p><%= @product.description %></p>
<p>
    Price: <b><%= @product.price %></b>
</p>
<p>
    <b>Category: </b> <%= @product.category.name %>
</p>
<div>
    <%= link_to 'Back to list', admin_products_path %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop Admin</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/admin/navbar' %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/admin/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Shop Admin', admin_products_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Products', admin_products_path %></li>
        <li><%= link_to 'Categories', admin_categories_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'View shop', root_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/application/navbar' %>

<div class="container">

  <% flash.each do |type, message| %>
    <%= content_tag :div, message, class: "alert alert-#{type}" %>
  <% end %>

  <%= yield %>

</div>
</body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Shop', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- Pages links -->
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text">
            Logged in as <%= current_user.name %>
          </p>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if current_user.admin? %>
                  <li><%= link_to 'Admin Panel', admin_root_path %></li>
                <% end %>
                <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                <li><a href="#">View orders</a></li>
                <li class="divider"></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/products/index.html.erb
<div class="jumbotron">
  <h1>Welcome to Shop!</h1>
  <p>Here you can purchase all kinds of computer hardware for lowest prices. We sell from only trusted and large distributors,
  to fulfill all your DIY computer needs!</p>
  <p><a href="#" class="btn btn-primary btn-lg">Learn more</a></p>
</div>

<div class="row">

  <div class="col-sm-3">
    <div class="panel panel-default" id="cart">
      <div class="panel-heading">
        <h3 class="panel-title">Categories</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% Category.all.each do |category| %>
            <li><a href="#"><%= category.name %></a></li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="row">
      <div class="col-sm-12 products-pagination">
        <%= will_paginate @products %>
      </div>
    </div>

    <div class="row">
        <% @products.each do |product| %>

        <div class="col-sm-6 product-item">
          <div class="panel panel-default">
            <div class="panel-body">
              <h3><%= product.title %></h3>
              <div class="img" style="background-image: url('<%= image_path product_image(product.id) %>');"></div>
              <h4>$<%= product.price %></h4>
              <p>
                <button class="btn btn-default">View</button>
                <button class="btn btn-primary">Add to cart</button>
              </p>
            </div>
          </div>
        </div>

        <% end %>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <%= will_paginate @products %>
      </div>
    </div>
  </div>
  <div class="col-sm-3">
      <div class="panel panel-default" id="cart">
        <div class="panel-heading">
          <h3 class="panel-title">Cart</h3>
        </div>
        <div class="panel-body">
          Your cart is empty
        </div>
      </div>
  </div>
</div>

app/views/shared/_field_errors.html.erb
<% if object.errors[field_name].any? %>
    <ul class="error-messages">
      <% object.errors.full_messages_for(field_name).each do |error| %>
          <li><%= error %></li>
      <% end %>
    </ul>
<% end %>